// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niturzmlsqincqhldcne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pdHVyem1sc3FpbmNxaGxkY25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzY0ODQsImV4cCI6MjA3MDA1MjQ4NH0.xZViRE8PkWx3rIOZRWCapCLZpw7wnzLkw7Fzi0Izt-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});